# name: hola-mundo
# on: 
#   push:
#     branches:
#       - main
#       - 'releases/**'
# jobs:
#   my-job-sp:
#     runs-on: self-hosted
#     steps:
#       - name: my-step
#         run: echo "Hello World!"
#       - name: Lista de directorios
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."
#   otro-job-sp:
#     runs-on: self-hosted
#     steps:
#       - name: my-paso
#         run: echo "Mi Paso"
        
